version: '3.7'

# To access data postgres writes within container from host machine
volumes:
  postgres_data: {}

services:
  db:
    image: postgres:11-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: $DB_PASSWORD
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  app:
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
      args:
        RAILS_ENV: $RAILS_ENV
    depends_on:
      - db
      - redis
    volumes:
      - '.:/var/www/my_app'
    ports:
      - "3000:3000"

  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
      args:
        RAILS_ENV: $RAILS_ENV

    depends_on:
      - app

    ports:
      - 80:80
