default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: <%= ENV['DB_PASSWORD'] %>
  pool: 5
  # host: db 
  host: localhost

development:
  <<: *default
  database: my_app_development
